// This file is auto-generated by scripts/generate-icon-imports.mjs

import analyticsOutline from '~icons/material-symbols-light/analytics-outline';
import api from '~icons/material-symbols-light/api';
import areaChartOutline from '~icons/material-symbols-light/area-chart-outline';
import brandAwarenessOutline from '~icons/material-symbols-light/brand-awareness-outline';
import businessCenterOutline from '~icons/material-symbols-light/business-center-outline';
import casesOutline from '~icons/material-symbols-light/cases-outline';
import chartDataOutline from '~icons/material-symbols-light/chart-data-outline';
import checkBoxOutline from '~icons/material-symbols-light/check-box-outline';
import cloudDoneOutline from '~icons/material-symbols-light/cloud-done-outline';
import cloudLockOutline from '~icons/material-symbols-light/cloud-lock-outline';
import code from '~icons/material-symbols-light/code';
import codeBlocksOutline from '~icons/material-symbols-light/code-blocks-outline';
import contractOutline from '~icons/material-symbols-light/contract-outline';
import dashboardOutline from '~icons/material-symbols-light/dashboard-outline';
import deployedCodeAccountOutline from '~icons/material-symbols-light/deployed-code-account-outline';
import deployedCodeAlertOutline from '~icons/material-symbols-light/deployed-code-alert-outline';
import deployedCodeOutline from '~icons/material-symbols-light/deployed-code-outline';
import deployedCodeUpdateOutline from '~icons/material-symbols-light/deployed-code-update-outline';
import designServicesOutline from '~icons/material-symbols-light/design-services-outline';
import editDocumentOutline from '~icons/material-symbols-light/edit-document-outline';
import flag2Outline from '~icons/material-symbols-light/flag-2-outline';
import folderCodeOutline from '~icons/material-symbols-light/folder-code-outline';
import gavelRounded from '~icons/material-symbols-light/gavel-rounded';
import globeBookRounded from '~icons/material-symbols-light/globe-book-rounded';
import handshakeOutline from '~icons/material-symbols-light/handshake-outline';
import integrationInstructionsOutline from '~icons/material-symbols-light/integration-instructions-outline';
import listAltOutline from '~icons/material-symbols-light/list-alt-outline';
import manageAccountsOutline from '~icons/material-symbols-light/manage-accounts-outline';
import moneyBagOutline from '~icons/material-symbols-light/money-bag-outline';
import psychologyOutline from '~icons/material-symbols-light/psychology-outline';
import rocketLaunchOutline from '~icons/material-symbols-light/rocket-launch-outline';
import schoolOutline from '~icons/material-symbols-light/school-outline';
import strategyOutline from '~icons/material-symbols-light/strategy-outline';
import trainOutline from '~icons/material-symbols-light/train-outline';
import trophyOutline from '~icons/material-symbols-light/trophy-outline';
import userAttributesOutline from '~icons/material-symbols-light/user-attributes-outline';

export const materialIcons = {
  'analytics-outline': analyticsOutline,
  'api': api,
  'area-chart-outline': areaChartOutline,
  'brand-awareness-outline': brandAwarenessOutline,
  'business-center-outline': businessCenterOutline,
  'cases-outline': casesOutline,
  'chart-data-outline': chartDataOutline,
  'check-box-outline': checkBoxOutline,
  'cloud-done-outline': cloudDoneOutline,
  'cloud-lock-outline': cloudLockOutline,
  'code': code,
  'code-blocks-outline': codeBlocksOutline,
  'contract-outline': contractOutline,
  'dashboard-outline': dashboardOutline,
  'deployed-code-account-outline': deployedCodeAccountOutline,
  'deployed-code-alert-outline': deployedCodeAlertOutline,
  'deployed-code-outline': deployedCodeOutline,
  'deployed-code-update-outline': deployedCodeUpdateOutline,
  'design-services-outline': designServicesOutline,
  'edit-document-outline': editDocumentOutline,
  'flag-2-outline': flag2Outline,
  'folder-code-outline': folderCodeOutline,
  'gavel-rounded': gavelRounded,
  'globe-book-rounded': globeBookRounded,
  'handshake-outline': handshakeOutline,
  'integration-instructions-outline': integrationInstructionsOutline,
  'list-alt-outline': listAltOutline,
  'manage-accounts-outline': manageAccountsOutline,
  'money-bag-outline': moneyBagOutline,
  'psychology-outline': psychologyOutline,
  'rocket-launch-outline': rocketLaunchOutline,
  'school-outline': schoolOutline,
  'strategy-outline': strategyOutline,
  'train-outline': trainOutline,
  'trophy-outline': trophyOutline,
  'user-attributes-outline': userAttributesOutline,
};
